<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'product_name' => 'iPhone 13',
                'product_code' => 'PRD001',
                'category_product_id' => 1,
                'brand_id' => 1,
                'description' => 'Latest Apple iPhone with advanced features.',
                'stock_quantity' => '100',
                'regular_price' => 9990000,
                'main_image' => 'public/uploads/product_images/1.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/3.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Samsung Galaxy S21',
                'product_code' => 'PRD002',
                'category_product_id' => 1,
                'brand_id' => 2,
                'description' => 'Flagship Samsung smartphone with superior camera.',
                'stock_quantity' => '50',
                'regular_price' => 8000000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/4.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Sony WH-1000XM4',
                'product_code' => 'PRD003',
                'category_product_id' => 2,
                'brand_id' => 3,
                'description' => 'Noise-cancelling wireless headphones from Sony.',
                'stock_quantity' => '75',
                'regular_price' => 4000000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Nike Air Zoom Pegasus',
                'product_code' => 'PRD004',
                'category_product_id' => 3,
                'brand_id' => 4,
                'description' => 'Running shoes with responsive cushioning.',
                'stock_quantity' => '150',
                'regular_price' => 1200000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Adidas Ultraboost 21',
                'product_code' => 'PRD005',
                'category_product_id' => 3,
                'brand_id' => 5,
                'description' => 'High-performance running shoes with energy return.',
                'stock_quantity' => '130',
                'regular_price' => 1800000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Microsoft Surface Laptop 4',
                'product_code' => 'PRD006',
                'category_product_id' => 1,
                'brand_id' => 6,
                'description' => 'Premium laptop from Microsoft with a sleek design.',
                'stock_quantity' => '90',
                'regular_price' => 9000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Google Pixel 6',
                'product_code' => 'PRD007',
                'category_product_id' => 1,
                'brand_id' => 7,
                'description' => 'Google’s latest smartphone with innovative features.',
                'stock_quantity' => '120',
                'regular_price' => 6000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg',
                'images' => '["public/uploads/product_images/3.jpg", "public/uploads/product_images/4.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Coca-Cola Can (12-Pack)',
                'product_code' => 'PRD008',
                'category_product_id' => 4,
                'brand_id' => 8,
                'description' => '12-pack of Coca-Cola cans, perfect for parties.',
                'stock_quantity' => '500',
                'regular_price' => 8000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Pepsi Bottle (24-Pack)',
                'product_code' => 'PRD009',
                'category_product_id' => 4,
                'brand_id' => 9,
                'description' => '24-pack of Pepsi bottles.',
                'stock_quantity' => '600',
                'regular_price' => 12000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Tesla Model S',
                'product_code' => 'PRD010',
                'category_product_id' => 5,
                'brand_id' => 10,
                'description' => 'Electric vehicle with advanced features.',
                'stock_quantity' => '5',
                'regular_price' => 700000000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'iPhone 13',
                'product_code' => 'PRD001',
                'category_product_id' => 1,
                'brand_id' => 1,
                'description' => 'Latest Apple iPhone with advanced features.',
                'stock_quantity' => '100',
                'regular_price' => 9990000,
                'main_image' => 'public/uploads/product_images/1.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/3.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Samsung Galaxy S21',
                'product_code' => 'PRD002',
                'category_product_id' => 1,
                'brand_id' => 2,
                'description' => 'Flagship Samsung smartphone with superior camera.',
                'stock_quantity' => '50',
                'regular_price' => 8000000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/4.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Sony WH-1000XM4',
                'product_code' => 'PRD003',
                'category_product_id' => 2,
                'brand_id' => 3,
                'description' => 'Noise-cancelling wireless headphones from Sony.',
                'stock_quantity' => '75',
                'regular_price' => 4000000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Nike Air Zoom Pegasus',
                'product_code' => 'PRD004',
                'category_product_id' => 3,
                'brand_id' => 4,
                'description' => 'Running shoes with responsive cushioning.',
                'stock_quantity' => '150',
                'regular_price' => 1200000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Adidas Ultraboost 21',
                'product_code' => 'PRD005',
                'category_product_id' => 3,
                'brand_id' => 5,
                'description' => 'High-performance running shoes with energy return.',
                'stock_quantity' => '130',
                'regular_price' => 1800000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Microsoft Surface Laptop 4',
                'product_code' => 'PRD006',
                'category_product_id' => 1,
                'brand_id' => 6,
                'description' => 'Premium laptop from Microsoft with a sleek design.',
                'stock_quantity' => '90',
                'regular_price' => 9000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Google Pixel 6',
                'product_code' => 'PRD007',
                'category_product_id' => 1,
                'brand_id' => 7,
                'description' => 'Google’s latest smartphone with innovative features.',
                'stock_quantity' => '120',
                'regular_price' => 6000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg',
                'images' => '["public/uploads/product_images/3.jpg", "public/uploads/product_images/4.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Coca-Cola Can (12-Pack)',
                'product_code' => 'PRD008',
                'category_product_id' => 4,
                'brand_id' => 8,
                'description' => '12-pack of Coca-Cola cans, perfect for parties.',
                'stock_quantity' => '500',
                'regular_price' => 8000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Pepsi Bottle (24-Pack)',
                'product_code' => 'PRD009',
                'category_product_id' => 4,
                'brand_id' => 9,
                'description' => '24-pack of Pepsi bottles.',
                'stock_quantity' => '600',
                'regular_price' => 12000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Tesla Model S',
                'product_code' => 'PRD010',
                'category_product_id' => 5,
                'brand_id' => 10,
                'description' => 'Electric vehicle with advanced features.',
                'stock_quantity' => '5',
                'regular_price' => 700000000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'iPhone 13',
                'product_code' => 'PRD001',
                'category_product_id' => 1,
                'brand_id' => 1,
                'description' => 'Latest Apple iPhone with advanced features.',
                'stock_quantity' => '100',
                'regular_price' => 9990000,
                'main_image' => 'public/uploads/product_images/1.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/3.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Samsung Galaxy S21',
                'product_code' => 'PRD002',
                'category_product_id' => 1,
                'brand_id' => 2,
                'description' => 'Flagship Samsung smartphone with superior camera.',
                'stock_quantity' => '50',
                'regular_price' => 8000000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/4.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Sony WH-1000XM4',
                'product_code' => 'PRD003',
                'category_product_id' => 2,
                'brand_id' => 3,
                'description' => 'Noise-cancelling wireless headphones from Sony.',
                'stock_quantity' => '75',
                'regular_price' => 4000000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Nike Air Zoom Pegasus',
                'product_code' => 'PRD004',
                'category_product_id' => 3,
                'brand_id' => 4,
                'description' => 'Running shoes with responsive cushioning.',
                'stock_quantity' => '150',
                'regular_price' => 1200000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Adidas Ultraboost 21',
                'product_code' => 'PRD005',
                'category_product_id' => 3,
                'brand_id' => 5,
                'description' => 'High-performance running shoes with energy return.',
                'stock_quantity' => '130',
                'regular_price' => 1800000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Microsoft Surface Laptop 4',
                'product_code' => 'PRD006',
                'category_product_id' => 1,
                'brand_id' => 6,
                'description' => 'Premium laptop from Microsoft with a sleek design.',
                'stock_quantity' => '90',
                'regular_price' => 9000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Google Pixel 6',
                'product_code' => 'PRD007',
                'category_product_id' => 1,
                'brand_id' => 7,
                'description' => 'Google’s latest smartphone with innovative features.',
                'stock_quantity' => '120',
                'regular_price' => 6000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg',
                'images' => '["public/uploads/product_images/3.jpg", "public/uploads/product_images/4.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Coca-Cola Can (12-Pack)',
                'product_code' => 'PRD008',
                'category_product_id' => 4,
                'brand_id' => 8,
                'description' => '12-pack of Coca-Cola cans, perfect for parties.',
                'stock_quantity' => '500',
                'regular_price' => 8000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Pepsi Bottle (24-Pack)',
                'product_code' => 'PRD009',
                'category_product_id' => 4,
                'brand_id' => 9,
                'description' => '24-pack of Pepsi bottles.',
                'stock_quantity' => '600',
                'regular_price' => 12000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Tesla Model S',
                'product_code' => 'PRD010',
                'category_product_id' => 5,
                'brand_id' => 10,
                'description' => 'Electric vehicle with advanced features.',
                'stock_quantity' => '5',
                'regular_price' => 700000000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'iPhone 13',
                'product_code' => 'PRD001',
                'category_product_id' => 1,
                'brand_id' => 1,
                'description' => 'Latest Apple iPhone with advanced features.',
                'stock_quantity' => '100',
                'regular_price' => 9990000,
                'main_image' => 'public/uploads/product_images/1.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/3.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Samsung Galaxy S21',
                'product_code' => 'PRD002',
                'category_product_id' => 1,
                'brand_id' => 2,
                'description' => 'Flagship Samsung smartphone with superior camera.',
                'stock_quantity' => '50',
                'regular_price' => 8000000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/4.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Sony WH-1000XM4',
                'product_code' => 'PRD003',
                'category_product_id' => 2,
                'brand_id' => 3,
                'description' => 'Noise-cancelling wireless headphones from Sony.',
                'stock_quantity' => '75',
                'regular_price' => 4000000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Nike Air Zoom Pegasus',
                'product_code' => 'PRD004',
                'category_product_id' => 3,
                'brand_id' => 4,
                'description' => 'Running shoes with responsive cushioning.',
                'stock_quantity' => '150',
                'regular_price' => 1200000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Adidas Ultraboost 21',
                'product_code' => 'PRD005',
                'category_product_id' => 3,
                'brand_id' => 5,
                'description' => 'High-performance running shoes with energy return.',
                'stock_quantity' => '130',
                'regular_price' => 1800000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Microsoft Surface Laptop 4',
                'product_code' => 'PRD006',
                'category_product_id' => 1,
                'brand_id' => 6,
                'description' => 'Premium laptop from Microsoft with a sleek design.',
                'stock_quantity' => '90',
                'regular_price' => 9000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Google Pixel 6',
                'product_code' => 'PRD007',
                'category_product_id' => 1,
                'brand_id' => 7,
                'description' => 'Google’s latest smartphone with innovative features.',
                'stock_quantity' => '120',
                'regular_price' => 6000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg',
                'images' => '["public/uploads/product_images/3.jpg", "public/uploads/product_images/4.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Coca-Cola Can (12-Pack)',
                'product_code' => 'PRD008',
                'category_product_id' => 4,
                'brand_id' => 8,
                'description' => '12-pack of Coca-Cola cans, perfect for parties.',
                'stock_quantity' => '500',
                'regular_price' => 8000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Pepsi Bottle (24-Pack)',
                'product_code' => 'PRD009',
                'category_product_id' => 4,
                'brand_id' => 9,
                'description' => '24-pack of Pepsi bottles.',
                'stock_quantity' => '600',
                'regular_price' => 12000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Tesla Model S',
                'product_code' => 'PRD010',
                'category_product_id' => 5,
                'brand_id' => 10,
                'description' => 'Electric vehicle with advanced features.',
                'stock_quantity' => '5',
                'regular_price' => 700000000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'iPhone 13',
                'product_code' => 'PRD001',
                'category_product_id' => 1,
                'brand_id' => 1,
                'description' => 'Latest Apple iPhone with advanced features.',
                'stock_quantity' => '100',
                'regular_price' => 9990000,
                'main_image' => 'public/uploads/product_images/1.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/3.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Samsung Galaxy S21',
                'product_code' => 'PRD002',
                'category_product_id' => 1,
                'brand_id' => 2,
                'description' => 'Flagship Samsung smartphone with superior camera.',
                'stock_quantity' => '50',
                'regular_price' => 8000000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/4.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Sony WH-1000XM4',
                'product_code' => 'PRD003',
                'category_product_id' => 2,
                'brand_id' => 3,
                'description' => 'Noise-cancelling wireless headphones from Sony.',
                'stock_quantity' => '75',
                'regular_price' => 4000000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Nike Air Zoom Pegasus',
                'product_code' => 'PRD004',
                'category_product_id' => 3,
                'brand_id' => 4,
                'description' => 'Running shoes with responsive cushioning.',
                'stock_quantity' => '150',
                'regular_price' => 1200000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Adidas Ultraboost 21',
                'product_code' => 'PRD005',
                'category_product_id' => 3,
                'brand_id' => 5,
                'description' => 'High-performance running shoes with energy return.',
                'stock_quantity' => '130',
                'regular_price' => 1800000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Microsoft Surface Laptop 4',
                'product_code' => 'PRD006',
                'category_product_id' => 1,
                'brand_id' => 6,
                'description' => 'Premium laptop from Microsoft with a sleek design.',
                'stock_quantity' => '90',
                'regular_price' => 9000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Google Pixel 6',
                'product_code' => 'PRD007',
                'category_product_id' => 1,
                'brand_id' => 7,
                'description' => 'Google’s latest smartphone with innovative features.',
                'stock_quantity' => '120',
                'regular_price' => 6000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg',
                'images' => '["public/uploads/product_images/3.jpg", "public/uploads/product_images/4.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Coca-Cola Can (12-Pack)',
                'product_code' => 'PRD008',
                'category_product_id' => 4,
                'brand_id' => 8,
                'description' => '12-pack of Coca-Cola cans, perfect for parties.',
                'stock_quantity' => '500',
                'regular_price' => 8000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Pepsi Bottle (24-Pack)',
                'product_code' => 'PRD009',
                'category_product_id' => 4,
                'brand_id' => 9,
                'description' => '24-pack of Pepsi bottles.',
                'stock_quantity' => '600',
                'regular_price' => 12000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Tesla Model S',
                'product_code' => 'PRD010',
                'category_product_id' => 5,
                'brand_id' => 10,
                'description' => 'Electric vehicle with advanced features.',
                'stock_quantity' => '5',
                'regular_price' => 700000000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'iPhone 13',
                'product_code' => 'PRD001',
                'category_product_id' => 1,
                'brand_id' => 1,
                'description' => 'Latest Apple iPhone with advanced features.',
                'stock_quantity' => '100',
                'regular_price' => 9990000,
                'main_image' => 'public/uploads/product_images/1.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/3.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Samsung Galaxy S21',
                'product_code' => 'PRD002',
                'category_product_id' => 1,
                'brand_id' => 2,
                'description' => 'Flagship Samsung smartphone with superior camera.',
                'stock_quantity' => '50',
                'regular_price' => 8000000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/4.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Sony WH-1000XM4',
                'product_code' => 'PRD003',
                'category_product_id' => 2,
                'brand_id' => 3,
                'description' => 'Noise-cancelling wireless headphones from Sony.',
                'stock_quantity' => '75',
                'regular_price' => 4000000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Nike Air Zoom Pegasus',
                'product_code' => 'PRD004',
                'category_product_id' => 3,
                'brand_id' => 4,
                'description' => 'Running shoes with responsive cushioning.',
                'stock_quantity' => '150',
                'regular_price' => 1200000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Adidas Ultraboost 21',
                'product_code' => 'PRD005',
                'category_product_id' => 3,
                'brand_id' => 5,
                'description' => 'High-performance running shoes with energy return.',
                'stock_quantity' => '130',
                'regular_price' => 1800000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Microsoft Surface Laptop 4',
                'product_code' => 'PRD006',
                'category_product_id' => 1,
                'brand_id' => 6,
                'description' => 'Premium laptop from Microsoft with a sleek design.',
                'stock_quantity' => '90',
                'regular_price' => 9000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Google Pixel 6',
                'product_code' => 'PRD007',
                'category_product_id' => 1,
                'brand_id' => 7,
                'description' => 'Google’s latest smartphone with innovative features.',
                'stock_quantity' => '120',
                'regular_price' => 6000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg',
                'images' => '["public/uploads/product_images/3.jpg", "public/uploads/product_images/4.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Coca-Cola Can (12-Pack)',
                'product_code' => 'PRD008',
                'category_product_id' => 4,
                'brand_id' => 8,
                'description' => '12-pack of Coca-Cola cans, perfect for parties.',
                'stock_quantity' => '500',
                'regular_price' => 8000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Pepsi Bottle (24-Pack)',
                'product_code' => 'PRD009',
                'category_product_id' => 4,
                'brand_id' => 9,
                'description' => '24-pack of Pepsi bottles.',
                'stock_quantity' => '600',
                'regular_price' => 12000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Tesla Model S',
                'product_code' => 'PRD010',
                'category_product_id' => 5,
                'brand_id' => 10,
                'description' => 'Electric vehicle with advanced features.',
                'stock_quantity' => '5',
                'regular_price' => 700000000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'iPhone 13',
                'product_code' => 'PRD001',
                'category_product_id' => 1,
                'brand_id' => 1,
                'description' => 'Latest Apple iPhone with advanced features.',
                'stock_quantity' => '100',
                'regular_price' => 9990000,
                'main_image' => 'public/uploads/product_images/1.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/3.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Samsung Galaxy S21',
                'product_code' => 'PRD002',
                'category_product_id' => 1,
                'brand_id' => 2,
                'description' => 'Flagship Samsung smartphone with superior camera.',
                'stock_quantity' => '50',
                'regular_price' => 8000000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/4.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Sony WH-1000XM4',
                'product_code' => 'PRD003',
                'category_product_id' => 2,
                'brand_id' => 3,
                'description' => 'Noise-cancelling wireless headphones from Sony.',
                'stock_quantity' => '75',
                'regular_price' => 4000000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Nike Air Zoom Pegasus',
                'product_code' => 'PRD004',
                'category_product_id' => 3,
                'brand_id' => 4,
                'description' => 'Running shoes with responsive cushioning.',
                'stock_quantity' => '150',
                'regular_price' => 1200000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Adidas Ultraboost 21',
                'product_code' => 'PRD005',
                'category_product_id' => 3,
                'brand_id' => 5,
                'description' => 'High-performance running shoes with energy return.',
                'stock_quantity' => '130',
                'regular_price' => 1800000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Microsoft Surface Laptop 4',
                'product_code' => 'PRD006',
                'category_product_id' => 1,
                'brand_id' => 6,
                'description' => 'Premium laptop from Microsoft with a sleek design.',
                'stock_quantity' => '90',
                'regular_price' => 9000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Google Pixel 6',
                'product_code' => 'PRD007',
                'category_product_id' => 1,
                'brand_id' => 7,
                'description' => 'Google’s latest smartphone with innovative features.',
                'stock_quantity' => '120',
                'regular_price' => 6000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg',
                'images' => '["public/uploads/product_images/3.jpg", "public/uploads/product_images/4.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Coca-Cola Can (12-Pack)',
                'product_code' => 'PRD008',
                'category_product_id' => 4,
                'brand_id' => 8,
                'description' => '12-pack of Coca-Cola cans, perfect for parties.',
                'stock_quantity' => '500',
                'regular_price' => 8000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Pepsi Bottle (24-Pack)',
                'product_code' => 'PRD009',
                'category_product_id' => 4,
                'brand_id' => 9,
                'description' => '24-pack of Pepsi bottles.',
                'stock_quantity' => '600',
                'regular_price' => 12000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Tesla Model S',
                'product_code' => 'PRD010',
                'category_product_id' => 5,
                'brand_id' => 10,
                'description' => 'Electric vehicle with advanced features.',
                'stock_quantity' => '5',
                'regular_price' => 700000000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'iPhone 13',
                'product_code' => 'PRD001',
                'category_product_id' => 1,
                'brand_id' => 1,
                'description' => 'Latest Apple iPhone with advanced features.',
                'stock_quantity' => '100',
                'regular_price' => 9990000,
                'main_image' => 'public/uploads/product_images/1.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/3.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Samsung Galaxy S21',
                'product_code' => 'PRD002',
                'category_product_id' => 1,
                'brand_id' => 2,
                'description' => 'Flagship Samsung smartphone with superior camera.',
                'stock_quantity' => '50',
                'regular_price' => 8000000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/4.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Sony WH-1000XM4',
                'product_code' => 'PRD003',
                'category_product_id' => 2,
                'brand_id' => 3,
                'description' => 'Noise-cancelling wireless headphones from Sony.',
                'stock_quantity' => '75',
                'regular_price' => 4000000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Nike Air Zoom Pegasus',
                'product_code' => 'PRD004',
                'category_product_id' => 3,
                'brand_id' => 4,
                'description' => 'Running shoes with responsive cushioning.',
                'stock_quantity' => '150',
                'regular_price' => 1200000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Adidas Ultraboost 21',
                'product_code' => 'PRD005',
                'category_product_id' => 3,
                'brand_id' => 5,
                'description' => 'High-performance running shoes with energy return.',
                'stock_quantity' => '130',
                'regular_price' => 1800000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Microsoft Surface Laptop 4',
                'product_code' => 'PRD006',
                'category_product_id' => 1,
                'brand_id' => 6,
                'description' => 'Premium laptop from Microsoft with a sleek design.',
                'stock_quantity' => '90',
                'regular_price' => 9000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Google Pixel 6',
                'product_code' => 'PRD007',
                'category_product_id' => 1,
                'brand_id' => 7,
                'description' => 'Google’s latest smartphone with innovative features.',
                'stock_quantity' => '120',
                'regular_price' => 6000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg',
                'images' => '["public/uploads/product_images/3.jpg", "public/uploads/product_images/4.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Coca-Cola Can (12-Pack)',
                'product_code' => 'PRD008',
                'category_product_id' => 4,
                'brand_id' => 8,
                'description' => '12-pack of Coca-Cola cans, perfect for parties.',
                'stock_quantity' => '500',
                'regular_price' => 8000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Pepsi Bottle (24-Pack)',
                'product_code' => 'PRD009',
                'category_product_id' => 4,
                'brand_id' => 9,
                'description' => '24-pack of Pepsi bottles.',
                'stock_quantity' => '600',
                'regular_price' => 12000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Tesla Model S',
                'product_code' => 'PRD010',
                'category_product_id' => 5,
                'brand_id' => 10,
                'description' => 'Electric vehicle with advanced features.',
                'stock_quantity' => '5',
                'regular_price' => 700000000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'iPhone 13',
                'product_code' => 'PRD001',
                'category_product_id' => 1,
                'brand_id' => 1,
                'description' => 'Latest Apple iPhone with advanced features.',
                'stock_quantity' => '100',
                'regular_price' => 9990000,
                'main_image' => 'public/uploads/product_images/1.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/3.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Samsung Galaxy S21',
                'product_code' => 'PRD002',
                'category_product_id' => 1,
                'brand_id' => 2,
                'description' => 'Flagship Samsung smartphone with superior camera.',
                'stock_quantity' => '50',
                'regular_price' => 8000000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/4.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Sony WH-1000XM4',
                'product_code' => 'PRD003',
                'category_product_id' => 2,
                'brand_id' => 3,
                'description' => 'Noise-cancelling wireless headphones from Sony.',
                'stock_quantity' => '75',
                'regular_price' => 4000000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Nike Air Zoom Pegasus',
                'product_code' => 'PRD004',
                'category_product_id' => 3,
                'brand_id' => 4,
                'description' => 'Running shoes with responsive cushioning.',
                'stock_quantity' => '150',
                'regular_price' => 1200000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Adidas Ultraboost 21',
                'product_code' => 'PRD005',
                'category_product_id' => 3,
                'brand_id' => 5,
                'description' => 'High-performance running shoes with energy return.',
                'stock_quantity' => '130',
                'regular_price' => 1800000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Microsoft Surface Laptop 4',
                'product_code' => 'PRD006',
                'category_product_id' => 1,
                'brand_id' => 6,
                'description' => 'Premium laptop from Microsoft with a sleek design.',
                'stock_quantity' => '90',
                'regular_price' => 9000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Google Pixel 6',
                'product_code' => 'PRD007',
                'category_product_id' => 1,
                'brand_id' => 7,
                'description' => 'Google’s latest smartphone with innovative features.',
                'stock_quantity' => '120',
                'regular_price' => 6000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg',
                'images' => '["public/uploads/product_images/3.jpg", "public/uploads/product_images/4.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Coca-Cola Can (12-Pack)',
                'product_code' => 'PRD008',
                'category_product_id' => 4,
                'brand_id' => 8,
                'description' => '12-pack of Coca-Cola cans, perfect for parties.',
                'stock_quantity' => '500',
                'regular_price' => 8000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Pepsi Bottle (24-Pack)',
                'product_code' => 'PRD009',
                'category_product_id' => 4,
                'brand_id' => 9,
                'description' => '24-pack of Pepsi bottles.',
                'stock_quantity' => '600',
                'regular_price' => 12000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Tesla Model S',
                'product_code' => 'PRD010',
                'category_product_id' => 5,
                'brand_id' => 10,
                'description' => 'Electric vehicle with advanced features.',
                'stock_quantity' => '5',
                'regular_price' => 700000000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'iPhone 13',
                'product_code' => 'PRD001',
                'category_product_id' => 1,
                'brand_id' => 1,
                'description' => 'Latest Apple iPhone with advanced features.',
                'stock_quantity' => '100',
                'regular_price' => 9990000,
                'main_image' => 'public/uploads/product_images/1.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/3.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Samsung Galaxy S21',
                'product_code' => 'PRD002',
                'category_product_id' => 1,
                'brand_id' => 2,
                'description' => 'Flagship Samsung smartphone with superior camera.',
                'stock_quantity' => '50',
                'regular_price' => 8000000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/4.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Sony WH-1000XM4',
                'product_code' => 'PRD003',
                'category_product_id' => 2,
                'brand_id' => 3,
                'description' => 'Noise-cancelling wireless headphones from Sony.',
                'stock_quantity' => '75',
                'regular_price' => 4000000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Nike Air Zoom Pegasus',
                'product_code' => 'PRD004',
                'category_product_id' => 3,
                'brand_id' => 4,
                'description' => 'Running shoes with responsive cushioning.',
                'stock_quantity' => '150',
                'regular_price' => 1200000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Adidas Ultraboost 21',
                'product_code' => 'PRD005',
                'category_product_id' => 3,
                'brand_id' => 5,
                'description' => 'High-performance running shoes with energy return.',
                'stock_quantity' => '130',
                'regular_price' => 1800000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Microsoft Surface Laptop 4',
                'product_code' => 'PRD006',
                'category_product_id' => 1,
                'brand_id' => 6,
                'description' => 'Premium laptop from Microsoft with a sleek design.',
                'stock_quantity' => '90',
                'regular_price' => 9000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Google Pixel 6',
                'product_code' => 'PRD007',
                'category_product_id' => 1,
                'brand_id' => 7,
                'description' => 'Google’s latest smartphone with innovative features.',
                'stock_quantity' => '120',
                'regular_price' => 6000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg',
                'images' => '["public/uploads/product_images/3.jpg", "public/uploads/product_images/4.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Coca-Cola Can (12-Pack)',
                'product_code' => 'PRD008',
                'category_product_id' => 4,
                'brand_id' => 8,
                'description' => '12-pack of Coca-Cola cans, perfect for parties.',
                'stock_quantity' => '500',
                'regular_price' => 8000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Pepsi Bottle (24-Pack)',
                'product_code' => 'PRD009',
                'category_product_id' => 4,
                'brand_id' => 9,
                'description' => '24-pack of Pepsi bottles.',
                'stock_quantity' => '600',
                'regular_price' => 12000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Tesla Model S',
                'product_code' => 'PRD010',
                'category_product_id' => 5,
                'brand_id' => 10,
                'description' => 'Electric vehicle with advanced features.',
                'stock_quantity' => '5',
                'regular_price' => 700000000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'iPhone 13',
                'product_code' => 'PRD001',
                'category_product_id' => 1,
                'brand_id' => 1,
                'description' => 'Latest Apple iPhone with advanced features.',
                'stock_quantity' => '100',
                'regular_price' => 9990000,
                'main_image' => 'public/uploads/product_images/1.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/3.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Samsung Galaxy S21',
                'product_code' => 'PRD002',
                'category_product_id' => 1,
                'brand_id' => 2,
                'description' => 'Flagship Samsung smartphone with superior camera.',
                'stock_quantity' => '50',
                'regular_price' => 8000000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/4.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Sony WH-1000XM4',
                'product_code' => 'PRD003',
                'category_product_id' => 2,
                'brand_id' => 3,
                'description' => 'Noise-cancelling wireless headphones from Sony.',
                'stock_quantity' => '75',
                'regular_price' => 4000000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Nike Air Zoom Pegasus',
                'product_code' => 'PRD004',
                'category_product_id' => 3,
                'brand_id' => 4,
                'description' => 'Running shoes with responsive cushioning.',
                'stock_quantity' => '150',
                'regular_price' => 1200000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Adidas Ultraboost 21',
                'product_code' => 'PRD005',
                'category_product_id' => 3,
                'brand_id' => 5,
                'description' => 'High-performance running shoes with energy return.',
                'stock_quantity' => '130',
                'regular_price' => 1800000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Microsoft Surface Laptop 4',
                'product_code' => 'PRD006',
                'category_product_id' => 1,
                'brand_id' => 6,
                'description' => 'Premium laptop from Microsoft with a sleek design.',
                'stock_quantity' => '90',
                'regular_price' => 9000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Google Pixel 6',
                'product_code' => 'PRD007',
                'category_product_id' => 1,
                'brand_id' => 7,
                'description' => 'Google’s latest smartphone with innovative features.',
                'stock_quantity' => '120',
                'regular_price' => 6000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg',
                'images' => '["public/uploads/product_images/3.jpg", "public/uploads/product_images/4.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Coca-Cola Can (12-Pack)',
                'product_code' => 'PRD008',
                'category_product_id' => 4,
                'brand_id' => 8,
                'description' => '12-pack of Coca-Cola cans, perfect for parties.',
                'stock_quantity' => '500',
                'regular_price' => 8000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Pepsi Bottle (24-Pack)',
                'product_code' => 'PRD009',
                'category_product_id' => 4,
                'brand_id' => 9,
                'description' => '24-pack of Pepsi bottles.',
                'stock_quantity' => '600',
                'regular_price' => 12000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Tesla Model S',
                'product_code' => 'PRD010',
                'category_product_id' => 5,
                'brand_id' => 10,
                'description' => 'Electric vehicle with advanced features.',
                'stock_quantity' => '5',
                'regular_price' => 700000000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'iPhone 13',
                'product_code' => 'PRD001',
                'category_product_id' => 1,
                'brand_id' => 1,
                'description' => 'Latest Apple iPhone with advanced features.',
                'stock_quantity' => '100',
                'regular_price' => 9990000,
                'main_image' => 'public/uploads/product_images/1.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/3.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Samsung Galaxy S21',
                'product_code' => 'PRD002',
                'category_product_id' => 1,
                'brand_id' => 2,
                'description' => 'Flagship Samsung smartphone with superior camera.',
                'stock_quantity' => '50',
                'regular_price' => 8000000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/4.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Sony WH-1000XM4',
                'product_code' => 'PRD003',
                'category_product_id' => 2,
                'brand_id' => 3,
                'description' => 'Noise-cancelling wireless headphones from Sony.',
                'stock_quantity' => '75',
                'regular_price' => 4000000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Nike Air Zoom Pegasus',
                'product_code' => 'PRD004',
                'category_product_id' => 3,
                'brand_id' => 4,
                'description' => 'Running shoes with responsive cushioning.',
                'stock_quantity' => '150',
                'regular_price' => 1200000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Adidas Ultraboost 21',
                'product_code' => 'PRD005',
                'category_product_id' => 3,
                'brand_id' => 5,
                'description' => 'High-performance running shoes with energy return.',
                'stock_quantity' => '130',
                'regular_price' => 1800000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Microsoft Surface Laptop 4',
                'product_code' => 'PRD006',
                'category_product_id' => 1,
                'brand_id' => 6,
                'description' => 'Premium laptop from Microsoft with a sleek design.',
                'stock_quantity' => '90',
                'regular_price' => 9000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Google Pixel 6',
                'product_code' => 'PRD007',
                'category_product_id' => 1,
                'brand_id' => 7,
                'description' => 'Google’s latest smartphone with innovative features.',
                'stock_quantity' => '120',
                'regular_price' => 6000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg',
                'images' => '["public/uploads/product_images/3.jpg", "public/uploads/product_images/4.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Coca-Cola Can (12-Pack)',
                'product_code' => 'PRD008',
                'category_product_id' => 4,
                'brand_id' => 8,
                'description' => '12-pack of Coca-Cola cans, perfect for parties.',
                'stock_quantity' => '500',
                'regular_price' => 8000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Pepsi Bottle (24-Pack)',
                'product_code' => 'PRD009',
                'category_product_id' => 4,
                'brand_id' => 9,
                'description' => '24-pack of Pepsi bottles.',
                'stock_quantity' => '600',
                'regular_price' => 12000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Tesla Model S',
                'product_code' => 'PRD010',
                'category_product_id' => 5,
                'brand_id' => 10,
                'description' => 'Electric vehicle with advanced features.',
                'stock_quantity' => '5',
                'regular_price' => 700000000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'iPhone 13',
                'product_code' => 'PRD001',
                'category_product_id' => 1,
                'brand_id' => 1,
                'description' => 'Latest Apple iPhone with advanced features.',
                'stock_quantity' => '100',
                'regular_price' => 9990000,
                'main_image' => 'public/uploads/product_images/1.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/3.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Samsung Galaxy S21',
                'product_code' => 'PRD002',
                'category_product_id' => 1,
                'brand_id' => 2,
                'description' => 'Flagship Samsung smartphone with superior camera.',
                'stock_quantity' => '50',
                'regular_price' => 8000000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/4.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Sony WH-1000XM4',
                'product_code' => 'PRD003',
                'category_product_id' => 2,
                'brand_id' => 3,
                'description' => 'Noise-cancelling wireless headphones from Sony.',
                'stock_quantity' => '75',
                'regular_price' => 4000000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Nike Air Zoom Pegasus',
                'product_code' => 'PRD004',
                'category_product_id' => 3,
                'brand_id' => 4,
                'description' => 'Running shoes with responsive cushioning.',
                'stock_quantity' => '150',
                'regular_price' => 1200000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/2.jpg", "public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Adidas Ultraboost 21',
                'product_code' => 'PRD005',
                'category_product_id' => 3,
                'brand_id' => 5,
                'description' => 'High-performance running shoes with energy return.',
                'stock_quantity' => '130',
                'regular_price' => 1800000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Microsoft Surface Laptop 4',
                'product_code' => 'PRD006',
                'category_product_id' => 1,
                'brand_id' => 6,
                'description' => 'Premium laptop from Microsoft with a sleek design.',
                'stock_quantity' => '90',
                'regular_price' => 9000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r98x-lq318qp9ypfpa9.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Google Pixel 6',
                'product_code' => 'PRD007',
                'category_product_id' => 1,
                'brand_id' => 7,
                'description' => 'Google’s latest smartphone with innovative features.',
                'stock_quantity' => '120',
                'regular_price' => 6000000,
                'main_image' => 'public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg',
                'images' => '["public/uploads/product_images/3.jpg", "public/uploads/product_images/4.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Coca-Cola Can (12-Pack)',
                'product_code' => 'PRD008',
                'category_product_id' => 4,
                'brand_id' => 8,
                'description' => '12-pack of Coca-Cola cans, perfect for parties.',
                'stock_quantity' => '500',
                'regular_price' => 8000,
                'main_image' => 'public/uploads/product_images/2.jpg',
                'images' => '["public/uploads/product_images/1.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Pepsi Bottle (24-Pack)',
                'product_code' => 'PRD009',
                'category_product_id' => 4,
                'brand_id' => 9,
                'description' => '24-pack of Pepsi bottles.',
                'stock_quantity' => '600',
                'regular_price' => 12000,
                'main_image' => 'public/uploads/product_images/3.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r98w-lpivvlvop9mgb2.jpg", "public/uploads/product_images/id-11134207-7r992-lq318qly3l1s82.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Tesla Model S',
                'product_code' => 'PRD010',
                'category_product_id' => 5,
                'brand_id' => 10,
                'description' => 'Electric vehicle with advanced features.',
                'stock_quantity' => '5',
                'regular_price' => 700000000,
                'main_image' => 'public/uploads/product_images/4.jpg',
                'images' => '["public/uploads/product_images/id-11134207-7r992-lq318qp9yp6gb0.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
